### ISSUE TITLE
Incorrect property name - testNamePattern

### ISSUE THREAD

**Issue by praveenpillai** [tornaia/karma-sonarqube-unit-reporter#20]
Example in plugin documentation indicates that the property to specify regexp pattern for the spec files is "testNamePattern" 
sonarQubeUnitReporter: {
      sonarQubeVersion: 'LATEST',
      outputFile: 'reports/ut_report.xml',
      overrideTestDescription: true,
      testPath: './test',
      **testNamePattern**: '.spec.js'
 },

But the actual name of the property is "testFilePattern" as indicated in line 199 of index.js
var testFilePattern = reporterConfig.**testFilePattern** || '(.spec.ts|.spec.js)'

Please correct the documentation at 
https://github.com/tornaia/karma-sonarqube-unit-reporter
and also at
https://www.npmjs.com/package/karma-sonarqube-unit-reporter

**Comment by tornaia** [comment]
Thanks for your input! Fixed in [PR#18](https://github.com/tornaia/karma-sonarqube-unit-reporter/pull/18). 

README.md was also updated there but it npmjs has issues with readme updates: https://github.com/npm/registry/issues/42
Until it's not being fixed I keep this issue open. In the meantime I'm trying to find an easy workaround for this issue.
